/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const CampaignStatus = IDL.Variant({
  'pending' : IDL.Null,
  'complete' : IDL.Null,
  'running' : IDL.Null,
});
export const Time = IDL.Int;
export const Campaign = IDL.Record({
  'id' : IDL.Nat,
  'status' : CampaignStatus,
  'completedAt' : IDL.Opt(Time),
  'name' : IDL.Text,
  'createdAt' : Time,
  'totalContacts' : IDL.Nat,
  'sentCount' : IDL.Nat,
  'message' : IDL.Text,
});
export const Contact = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'createdAt' : Time,
  'phone' : IDL.Text,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addContact' : IDL.Func([IDL.Text, IDL.Text], [IDL.Nat], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'bulkImportContacts' : IDL.Func(
      [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Text))],
      [],
      [],
    ),
  'createCampaign' : IDL.Func([IDL.Text, IDL.Text], [IDL.Nat], []),
  'deleteContact' : IDL.Func([IDL.Nat], [], []),
  'getAllCampaigns' : IDL.Func([], [IDL.Vec(Campaign)], ['query']),
  'getAllContacts' : IDL.Func([], [IDL.Vec(Contact)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCampaignById' : IDL.Func([IDL.Nat], [Campaign], ['query']),
  'getCampaignSends' : IDL.Func([IDL.Nat], [IDL.Vec(IDL.Nat)], ['query']),
  'getContactCount' : IDL.Func([], [IDL.Nat], ['query']),
  'getSendsByContact' : IDL.Func([IDL.Nat], [IDL.Vec(IDL.Nat)], ['query']),
  'getTodaySendCount' : IDL.Func([], [IDL.Nat], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'markCampaignComplete' : IDL.Func([IDL.Nat], [], []),
  'recordSend' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateCampaignProgress' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const CampaignStatus = IDL.Variant({
    'pending' : IDL.Null,
    'complete' : IDL.Null,
    'running' : IDL.Null,
  });
  const Time = IDL.Int;
  const Campaign = IDL.Record({
    'id' : IDL.Nat,
    'status' : CampaignStatus,
    'completedAt' : IDL.Opt(Time),
    'name' : IDL.Text,
    'createdAt' : Time,
    'totalContacts' : IDL.Nat,
    'sentCount' : IDL.Nat,
    'message' : IDL.Text,
  });
  const Contact = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'createdAt' : Time,
    'phone' : IDL.Text,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addContact' : IDL.Func([IDL.Text, IDL.Text], [IDL.Nat], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'bulkImportContacts' : IDL.Func(
        [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Text))],
        [],
        [],
      ),
    'createCampaign' : IDL.Func([IDL.Text, IDL.Text], [IDL.Nat], []),
    'deleteContact' : IDL.Func([IDL.Nat], [], []),
    'getAllCampaigns' : IDL.Func([], [IDL.Vec(Campaign)], ['query']),
    'getAllContacts' : IDL.Func([], [IDL.Vec(Contact)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCampaignById' : IDL.Func([IDL.Nat], [Campaign], ['query']),
    'getCampaignSends' : IDL.Func([IDL.Nat], [IDL.Vec(IDL.Nat)], ['query']),
    'getContactCount' : IDL.Func([], [IDL.Nat], ['query']),
    'getSendsByContact' : IDL.Func([IDL.Nat], [IDL.Vec(IDL.Nat)], ['query']),
    'getTodaySendCount' : IDL.Func([], [IDL.Nat], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'markCampaignComplete' : IDL.Func([IDL.Nat], [], []),
    'recordSend' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateCampaignProgress' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
  });
};

export const init = ({ IDL }) => { return []; };